version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.4
  # aws-s3: circleci/aws-s3@3.1.1

executors:
  oldnode:
    docker:
      - image: circleci/node:8.11.2
    resource_class: small

jobs:
  cp:
    executor: onenode
    steps:
      - checkout
      - aws-cli/setup
      - run: aws --version
      # - aws-s3/copy:
      #     install-aws-cli: false
      #     arguments: |
      #       --cache-control \"max-age=15\" \
      #       --acl bucket-owner-full-control
      #     from: README.md
      #     to: "s3://aws-s3-orb-explore/source-code/"

workflows:
  main:
    jobs:
      - cp
