version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.4
  aws-s3: circleci/aws-s3@3.1.1

jobs:
  cp:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - aws-s3/copy:
          install-aws-cli: false
          arguments: |
            --cache-control "public, max-age=15" \
            --acl bucket-owner-full-control
          from: README.md
          to: "s3://aws-s3-orb-explore/source-code/"

workflows:
  main:
    jobs:
      - cp
